In [3]:
import numpy as np
age = np.array([23,56,98,43,21,48])
print(age)

[23 56 98 43 21 48]


In [4]:
age = np.array([[23],[56],[98],[43],[21],[48]])
print(age)

[[23]
 [56]
 [98]
 [43]
 [21]
 [48]]


In [5]:
age = np.array([[23,170,85],[56,175,89],[98,169,78],[43,186,90],[21,167,76],[48,79,90]])
print(age)

[[ 23 170  85]
 [ 56 175  89]
 [ 98 169  78]
 [ 43 186  90]
 [ 21 167  76]
 [ 48  79  90]]


In [6]:
age.shape

(6, 3)

In [36]:
age[0:3, :2]


array([[ 23, 170],
       [ 56, 175],
       [ 98, 169]])

In [22]:
#[rows , columns]
#[start : end , start : end]
age[:,0:1]

array([[23],
       [56],
       [98],
       [43],
       [21],
       [48]])

In [9]:
print("Mean:",np.mean(age[:,0:1]))
print("Median:",np.median(age[:,0:1]))
print("std:",np.std(age[:,0:1]))
print("var:",np.var(age[:,0:1]))
print("Mean:",np.min(age[:,0:1]))
print("Mean:",np.max(age[:,0:1]))

Mean: 48.166666666666664
Median: 45.5
std: 25.634720378597635
var: 657.1388888888889
Mean: 21
Mean: 98


In [10]:
age[ : ,1:2]

array([[170],
       [175],
       [169],
       [186],
       [167],
       [ 79]])

In [24]:
x = np.random.randint(10,50, size=6)
x

array([15, 49, 17, 30, 44, 44])

In [27]:
x = np.random.randint(10,50, size=6)
x

array([12, 44, 13, 47, 24, 27])

In [28]:
x = np.random.randint(10,50, size=(2,3))
x

array([[32, 40, 30],
       [22, 41, 20]])

In [37]:
x = np.random.randint(1111,9999, size=1)
x

array([8334])

In [29]:
x.ndim

2